#! /bin/sh
BATC=/sys/class/power_supply/BAT1/capacity
BATS=/sys/class/power_supply/BAT1/status

function expandstr {
	if [ $# -gt 1 ]; then
		export COMP=$(expr $2 - ${#1})
		comp_str=$(perl -e 'print(" "x$ENV{COMP})')
		echo "$1$comp_str"
	elif [ $# -gt 0 ]; then
		export COMP=$1
		comp_str=$(perl -e 'print(" "x$ENV{COMP})')
		echo "$comp_str"
	fi
}	

## STATIC BAR ELEMENTS

function window_icon {
	if [[ "$1" == 'urxvt' ]]; then	
		echo -e "\uf120"
	elif [[ "$1" == 'google-chrome' ]]; then
		echo -e "\uf2b3"
	else	
		echo -e "\uf00a"
	fi
}

function window {	
	wnd_focus=$(xdotool getwindowfocus)                                                                                                                         
	wnd_title=$(xprop -id $wnd_focus WM_CLASS |\
		  grep -Po "\".*?\"" |\
		  head -1 |\
		  grep -Po "[^\"]*")
	
	echo -e "%{B#33CCDD}%{O20}$(window_icon $wnd_title) $(expandstr $wnd_title 15)%{B-}"
}

function timeday {
	echo "%{c}$(clock)"
}

function battery {
	echo "%{r}$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		    grep -oE "[0-9]*%" |\
		    grep -oP "\d*" |\
		    head -1)%%{O10}"
}

while [ 1 -gt 0 ]; do	
	echo -e "$(window)$(timeday)$(battery)"
	sleep .1
done
