#! /bin/sh
LIGHT=0

BATC=./sys/class/power_supply/BAT1/capacity
BATS=./sys/class/power_supply/BAT1/status

#Foreground color
fgc=#FFFFFF

#Highlight color
hlc=#50CFDA

if [[ $LIGHT == 0 ]]; then
	fgc=#333333
fi

function expandstr {
	if [ $# -gt 1 ]; then
		export COMP=$(expr $2 - ${#1})
		comp_str=$(perl -e 'print(" "x$ENV{COMP})')
		echo "$1$comp_str"
	elif [ $# -gt 0 ]; then
		export COMP=$1
		comp_str=$(perl -e 'print(" "x$ENV{COMP})')
		echo "$comp_str"
	fi
}	

function username {
	echo $USER
}

function get_window {
	winid=$(bspc query -D -d)
	win_num="${winid: -1}"

	if [ "$win_num" == "3" ]; then	
		echo -e "%{F$hlc}main%{F-}  %{F$fgc}dev%{F-}  %{F$fgc}web%{F-}  %{F$fgc}music%{F-}  %{F$fgc}etc%{F-}"
	elif [ "$win_num" == "4" ]; then
		echo -e "%{F$fgc}main%{F-}  %{F$hlc}dev%{F-}  %{F$fgc}web%{F-}  %{F$fgc}music%{F-}  %{F$fgc}etc%{F-}"	
	elif [ "$win_num" == "5" ]; then
		echo -e "%{F$fgc}main%{F-}  %{F$fgc}dev%{F-}  %{F$hlc}web%{F-}  %{F$fgc}music%{F-}  %{F$fgc}etc%{F-}"
	elif [ "$win_num" == "6" ]; then
		echo -e "%{F$fgc}main%{F-}  %{F$fgc}dev%{F-}  %{F$fgc}web%{F-}  %{F$hlc}music%{F-}  %{F$fgc}etc%{F-}"
	else
		echo -e "%{F$fgc}main%{F-}  %{F$fgc}dev%{F-}  %{F$fgc}web%{F-}  %{F$fgc}music%{F-}  %{F$hlc}etc%{F-}"
	fi
}


function window_icon {
	if [[ "$1" == 'urxvt' ]]; then	
		echo -e "\uf120"
	elif [[ "$1" == 'chrome' ]]; then
		echo -e "\uf268"
	elif [[ "$1" == 'firefox' ]]; then
		echo -e "\uf269"
	elif [[ "$1" == 'desktop' ]]; then
		echo -e "\uf108"
	elif [[ "$1" == 'nautilus' ]]; then
		echo -e "\uf07b"
	elif [[ "$1" == 'atom' ]]; then
		echo -e "\uf121"
	else	
		echo -e "\uf17c"
	fi
}
function window {	
	wnd_focus=$(xdotool getwindowfocus)                                                                                                                         
	wnd_title=$(xprop -id $wnd_focus WM_CLASS |\
		  grep -Po "\".*?\"" |\
		  head -1 |\
		  grep -Po "[^\"]*")

	wnd_name=$(xprop -id $wnd_focus WM_NAME |\
		   grep -Po "\".*\"" |\
		   head -1 |\
		   grep -Po "[^\"]*")
	if [[ "$wnd_title" == 'Navigator' ]]; then
		wnd_title='firefox'
	elif [[ "$wnd_title" == 'google-chrome' ]]; then
		wnd_title='chrome'
	elif [[ "$wnd_title" == '' ]]; then
		wnd_title='desktop'
	fi

	echo -e "%{F$fgc}%{U#237889}%{O20}$(window_icon $wnd_title) $(expandstr $wnd_title 15)%{U-}%{F-}"
}

function timeday {
	timed=$(clock | grep -o "[0-9]*:[0-9]*")
	hour=$(echo $timed | grep -oP "^[0-9]*")
	min=$(echo $timed | grep -oP "[0-9]*$")
	mdhr=$((10#$hour % 12))
	mdhr=11
	part="AM"
	if [[ "$hour" > 11 ]]; then
		part="PM"
	fi
	if [[ "$mdhr" == 0 ]]; then
		mdhr=12
	fi

	echo -e "%{F$fgc}$hour:$min $part%{F-}"
}

function battery {
	batlvl="$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		    grep -oE "[0-9]*%" |\
		    grep -oP "\d*" |\
		    head -1)"

	charging="$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		    grep "state: *charging\|state: *fully")"
	state=""
	if [[ ${#charging} -gt 0 ]]; then
		state="%{F$hlc}"
	else
		state="%{F$fgc}"
	fi

	if [[ $batlvl -gt 87 ]]; then
		echo "$state$batlvl% \uf240%{F-}"
	elif [[ $batlvl -gt 63 ]]; then
		echo "$state$batlvl% \uf241%{F-}"
	elif [[ $batlvl -gt 37 ]]; then
		echo "$state$batlvl% \uf242%{F-}"
	elif [[ $batlvl -gt 13 ]]; then
		echo "$state$batlvl% \uf243%{F-}"
	else
		echo "$state$batlvl% \uf244%{F-}"
	fi
}

function active {
	echo "\uf111 \uf10c"
}

while [ 1 -gt 0 ]; do
	
	f="%{l}%{O10}$(window)"
	c="%{c}$(get_window)"
	b="%{r}$(battery) $(timeday)%{O10}"

	echo -e "$f$c$b"
	sleep .1
done
