#!/bin/bash
OUT=false

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=60
PANEL_FONT="Sauce\ Code\ Powerline:size=16"
PANEL_WM_NAME=bspwm_panel
BG_COLOR="#222A35"
FG_COLOR="#FFFFFF"


if [ $OUT == true ]; then 	
	bspc config top_padding $(expr 2 \* $PANEL_HEIGHT)
	bar_input | lemonbar -n "$PANEL_WM_NAME"\
		             -g 3100x$PANEL_HEIGHT+50+50\
			     -f "$PANEL_FONT"\
			     -f "FontAwesome:size=19"\
			     -B "$BG_COLOR"\
			     -F "$FG_COLOR" 2> /dev/null
else
	bspc config top_padding $PANEL_HEIGHT
	bar_input | lemonbar -n "$PANEL_WM_NAME"\
		             -g 3120x$PANEL_HEIGHT+40\
			     -f "$PANEL_FONT"\
			     -f "FontAwesome:size=19"\
			     -F "$FG_COLOR" 2> /dev/null
fi
